#!/usr/bin/env bash
# stops 4-to_infinity_and_beyond process using kill

pid=$(pgrep -f '4-to_infinity_and_beyond')

if [ -n "$pid" ]; then
    # Use kill command to terminate the process with the obtained PID
    kill "$pid"
    echo "Process '4-to_infinity_and_beyond' (PID: $pid) has been stopped."
else
    echo "Process '4-to_infinity_and_beyond' is not running."
fi
